CREATE DATABASE Venda_GET;
USE Venda_GET;
CREATE TABLE precos_get (ide INT PRIMARY KEY AUTO_INCREMENT, SKU VARCHAR(50) NOT NULL, 
produto VARCHAR(100) NOT NULL, preco DEC(4,2) NOT NULL, quantidade INT NOT NULL);

CREATE TABLE vendas_get(ident INT PRIMARY KEY AUTO_INCREMENT, cupom VARCHAR(10) DEFAULT '0', 
SKU VARCHAR(50) NOT NULL, produto VARCHAR(100) NOT NULL, 
preco DEC(4,2), forma_pagamento VARCHAR(60) NOT NULL, data_compra DATETIME DEFAULT current_timestamp); 

CREATE TABLE clientes_get3(cupom VARCHAR(10) PRIMARY KEY DEFAULT '0', CPF CHAR(11) NOT NULL UNIQUE,
Nome VARCHAR(100) NOT NULL,
Telefone VARCHAR(11), Logradouro VARCHAR(150), Cidade VARCHAR(50), Estado VARCHAR(40));